### PR TITLE
Check the status on DBConnection.run

### LINKED ISSUE #122: DBConnection.run should fail if the connection state before and after are not the same

### PR DESCRIPTION
**Pull request by josevalim**
Closes #122.

### CODE REVIEW

File: integration_test/cases/client_test.exs [hunk 1]
```diff
@@ -127,26 +152,30 @@ defmodule ClientTest do
...
         P.execute(conn, %Q{}, [:param])
-      end, [timeout: 0])
+      end, [timeout: 100])
     catch
       :throw, :oops ->
         :ok
     end
 
-    assert_receive :done
+    spawn_link(fn ->
```
Comment (fishcakez) [inline integration_test/cases/client_test.exs]: Don't need to spawn link here? Though comment above should handle the test and we dont need this.

File: integration_test/cases/transaction_test.exs [hunk 2]
```diff
@@ -965,10 +965,7 @@ defmodule TransactionTest do
 
     assert P.status(pool, opts) == :idle
     assert P.status(pool, opts) == :transaction
-    assert P.run(pool, fn(conn) ->
-      assert P.status(pool, [queue: false] ++ opts) == :error
-      assert P.status(conn, opts)
-    end, opts)
+    assert P.status(pool, [queue: false] ++ opts) == :error
```
Comment (fishcakez) [inline integration_test/cases/transaction_test.exs]: Thus doesn't test same thing, this test is that we get an `:error` atom when can't checkout from pool - so that handle_status is not called for this one.

File: integration_test/cases/client_test.exs [hunk 3]
```diff
@@ -127,26 +152,30 @@ defmodule ClientTest do
     try do
       P.run(pool, fn(conn) ->
         assert_receive :reconnected
-        spawn_link(fn() ->
```
Comment (fishcakez) [inline integration_test/cases/client_test.exs]: We want to spawn_link here so that checkout occurs before `run` or `execute` has chance to fail/checkin. I think this previous code should work with timeout of `100`.

File: integration_test/cases/idle_test.exs [hunk 4]
```diff
@@ -29,12 +29,11 @@ defmodule TestIdle do
     {:ok, agent} = A.start_link(stack)
 
     opts = [agent: agent, parent: self(), idle_timeout: 50, idle_interval: 50]
-    {:ok, pool} = P.start_link(opts)
+    {:ok, _} = P.start_link(opts)
     assert_receive {:hi, conn}
     assert_receive {:pong, ^conn}
     assert_receive {:pong, ^conn}
     send(conn, {:continue, self()})
-    P.run(pool, fn(_) -> :ok end)
```
Comment (fishcakez) [inline integration_test/cases/idle_test.exs]: Are we able to keep this? The test ensures we resume pings after checking back in.

File: integration_test/cases/client_test.exs (hunk 3 above)
Comment (josevalim) [reply integration_test/cases/client_test.exs]: It didn't work with a higher timeout either. There is a race on which arguments are popped from the agent.

File: integration_test/cases/transaction_test.exs (hunk 2 above)
Comment (josevalim) [reply integration_test/cases/transaction_test.exs]: I moved this test below: https://github.com/elixir-ecto/db_connection/pull/145/files#diff-c000545f7e7485c4bc7ed2cc55e6f5b8R1021

File: integration_test/cases/idle_test.exs (hunk 4 above)
Comment (josevalim) [reply integration_test/cases/idle_test.exs]: I don't know why it was removed actually. I will investigate.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
